const Khodam = ()=> {
    return[
  'Jin Bertuah',
  'Ratu Kidul',
  'Buto Ijo',
  'Nyai Roro Kidul',
  'Kuntilanak',
  'Tuyul',
  'Genderuwo',
  'Bunian',
  'Jin Pendamping',
  'Sangkuriang',
  'Putri Duyung',
  'Pocong',
  'Sundel Bolong',
  'Wewe Gombel',
  'Keris Taming Sari',
  'Keris Pusaka',
  'Kuntilanak Ciliwung',
  'Mang Jaya Raya',
  'Bidadari Surga',
  'Cuplikan Cermin',
  'Bang Lelono',
  'Mak Lampir',
  'Keris Setan Kober',
  'Buta Ijo',
  'Prabu Kiansantang',
  'Jaka Tarub',
  'Loro Jonggrang',
  'Barong',
  'Kumbakarna',
  'Kera Tumpai',
  'Sugriwa',
  'Wibisana',
  'Gatotkaca',
  'Semar',
  'Gareng',
  'Petruk',
  'Bagong',
  'Bambang Irawan',
  'Sabdo Palon',
  'Kuncung Putih',
  'Patih Dinar',
  'Aji Saka',
  'Pangeran Diponegoro',
  'Kanjeng Ratu Kidul',
  'Jin Ganas',
  'Jin Kafir',
  'Jin Jelmaan',
  'Tuyul Hampir',
  'Burung Garuda',
  'Sarang Monyet',
  'Lintah Darat',
  'Penghuni Hutan',
  'Makhluk Gaib',
  'Jelmaan Putri Duyung',
  'Sasangka Raja',
  'Sakrasna Tanpa Tugu',
  'Tuyul Sungsang',
  'Jin Lingsa',
  'Setan Tuyul',
  'Burung Hantu',
  'Kelelawar',
  'Kutuk Selatan',
  'Burung Garuda',
  'Sangkuriang Laut',
  'Roro Jonggrang',
  'Jaka Tarub',
  'Loro Kidul',
  'Sakral Tanpa Pamor',
  'Kala Tanpa Batas'
]}

export default Khodam
